#!/bin/sh

# Created at: 2025-03-09_1409
# By: penguins_eggs v. 10.0.60
# ==> Perri's Brewery edition <== 

xorriso -as mkisofs -J -joliet-long -l -iso-level 3 -isohybrid-mbr /usr/lib/penguins-eggs/syslinux/isohdpfx.bin -partition_offset 16 -V debian -b isolinux/isolinux.bin -c isolinux/boot.cat -no-emul-boot -boot-load-size 4 -boot-info-table -eltorito-alt-boot -e boot/grub/efi.img -isohybrid-gpt-basdat -no-emul-boot -o /home/eggs/.mnt/egg-of_sunos-trixie-debian_amd64_2025-03-09_1409.iso /home/eggs/.mnt/iso/
