#!/bin/sh

# Created at: 2025-03-09_1407
# By: penguins_eggs v. 10.0.60
# ==> Perri's Brewery edition <== 

mksquashfs /home/eggs/.mnt/filesystem.squashfs /home/eggs/.mnt/iso/live/filesystem.squashfs -comp zstd -b 1M -Xcompression-level 15 -wildcards -ef /etc/penguins-eggs.d/exclude.list -e 'boot/efi/EFI' 'boot/loader/entries/' 'etc/fstab' 'etc/mtab' 'etc/udev/rules.d/70-persistent-cd.rules' 'etc/udev/rules.d/70-persistent-net.rules' 'etc/rc0.dK01cryptdisks' 'etc/rc0.dK01cryptdisks-early' 'etc/rc6.dK01cryptdisks' 'etc/rc6.dK01cryptdisks-early' 'etc/rcS.dS01cryptdisks' 'etc/rcS.dS01cryptdisks-early' 'root/*' 'root/.*' 'home/eggs/'
